<?php
class AboutPageSchema extends GenericSchema
{
    public function mustRenderOnPage()
    {
        global $post;

        return $post !== null && Markapp_Schema_Matcher::isAboutPage($post); // TODO: Change the autogenerated stub
    }

    public function schema()
    {
        global $my_seo_settings_about_page_options;
        global $my_seo_settings_options;

        $data = [];

        $data["@context"] = "http://schema.org";
			$data["@type"] = ["WebPage","AboutPage"];
			$data["@id"] = "schema:Webpage";
		$data["mainEntity"] = [
			"@type" => "AboutPage",
			"@id" => "schema:AboutPage",
			"name" => "About Page"
		];
		$data["mainContentOfPage"] = [
			"@type" => "WebPageElement",
			"xpath" => ["/*/html/body/descendant-or-self::*/text()"]
		];
        $data["lastReviewed"] = get_the_modified_date( 'c' );
        $data["copyrightYear"] = $my_seo_settings_about_page_options['generate_json_ld_about_page_copyright_year'] ?? null;
        $data["headline"] = get_the_title();
        $data["relatedLink"] = $my_seo_settings_about_page_options['generate_json_ld_about_page_related_link'] ?? null;
        $data["specialty"] = array(
                "@type"  => "Specialty",
				"@id" => "schema:Specialty",
                "description" => $my_seo_settings_about_page_options['generate_json_ld_about_page_speciality_description'] ?? null,
                "name" => $my_seo_settings_about_page_options['generate_json_ld_about_page_speciality_name'] ?? null
            );
        $data["inLanguage"]  = [
                "@type" => "Language",
				"@id" => "schema:Language",		
                "name" => $my_seo_settings_options["generate_json_ld_fpwebpage_inlanguage"] ?? null 
            ];
            $data["primaryImageOfPage"] = get_the_post_thumbnail_url();

        return $data;
    }

    public function settings()
    {
        $settings = AboutPageSettings::instance();
        $settings->initDefaultSection();
        $settings->initSidebarSettingsPage(get_class($this));
        $settings->renderSidebarForm();
    }

}