<?php
class LocalBusinessSchema extends GenericSchema
{
    public function mustRenderOnPage()
    {
        global $post;

        return $post !== null && Markapp_Schema_Matcher::isLocalBusinessPage($post); // TODO: Change the autogenerated stub
    }

    public function schema()
    {
		
        $options = LocalBusinessSettings::instance()->getOptions();

        $data = [];

        $data["@context"] = "http://schema.org";
        $data["@type"] = [$options['generate_json_ld_lbloo'] ?? null, $options['generate_json_ld_lbtype'] ?? null];
        $data["@id"] = "schema:" . $options['generate_json_ld_lbtype'] ?? null;
		
        $openingHours = [];

        foreach ($options['opening_hours'] as $day1 => $times1) {
            if (empty($times1['opens']) || empty($times1['closes'])) {
                continue;
            }
            $openingHours = array(
                $day1,
                $times1['opens'] ?? null,
                $times1['closes'] ?? null
            );
        }
 foreach ($options['opening_hours'] as $day2 => $times2) {
            if (empty($times2['opens']) || empty($times2['closes'])) {
                continue;
            }
            $openingHours = array(
                $day2,
                $times2['opens'] ?? null,
                $times2['closes'] ?? null
            );
        }

			$data["additionalType"] = "LocalBusiness";
            $data["priceRange"] = $options['generate_json_ld_localbusiness_price_range'] ?? null;
            $data["telephone"] = $options['generate_json_ld_localbusiness_telephone'] ?? null;
            $data["name"] = $options['generate_json_ld_localbusiness_name'] ?? null;
            $data["url"] = $options['generate_json_ld_localbusiness_url'] ?? null;
            $data["image"] = array(
                "@type"  => "ImageObject",
                "url"    => $options['generate_json_ld_localbusiness_image_url'] ?? null);
            $data["description"] = $options['generate_json_ld_localbusiness_description'] ?? null;
            $data["location"] = array(
                "@type" => "PostalAddress",
				"@id" => "schema:PostalAddress",
                "streetAddress" => $options['generate_json_ld_localbusiness_address_street_address'] ?? null,
                "addressLocality" => $options['generate_json_ld_localbusiness_address_address_locality'] ?? null,
                "addressRegion" => $options['generate_json_ld_localbusiness_address_address_region'] ?? null,
                "postalCode" => $options['generate_json_ld_localbusiness_address_postal_code'] ?? null,
                "addressCountry" => $options['generate_json_ld_localbusiness_address_address_country'] ?? null
            );
            $data["areaServed"] = $options['generate_json_ld_localbusiness_location_area_served'] ?? null;
            $data["address"] = array (
                "@type" => "PostalAddress",
                "streetAddress" => $options['generate_json_ld_localbusiness_address_street_address'] ?? null,
                "addressLocality" => $options['generate_json_ld_localbusiness_address_address_locality'] ?? null,
                "addressRegion" => $options['generate_json_ld_localbusiness_address_address_region'] ?? null,
                "postalCode" => $options['generate_json_ld_localbusiness_address_postal_code'] ?? null,
                "addressCountry" => $options['generate_json_ld_localbusiness_address_address_country'] ?? null
            );
            $data["geo"] =  array(
                "@type" => "GeoCoordinates",
                "latitude" => $options['generate_json_ld_localbusiness_geo_latitude'] ?? null,
                "longitude" => $options['generate_json_ld_localbusiness_geo_longitude'] ?? null
            );
            $data["hasMap"] = array(
                "@type" => "Map",
                "url" => $options['generate_json_ld_localbusiness_has_map'] ?? null);
            $data["openingHours"] = $openingHours;
            $data["contactPoint"] = array(
                "@type" => "ContactPoint",
                "contactType" => "customer support",
                "telephone" => $options['generate_json_ld_localbusiness_contact_point_telephone'] ?? null,
                "email" => $options['generate_json_ld_localbusiness_contact_point_email'] ?? null
            );
            $data["brand"] = array(
                "@type" => $options['generate_json_ld_brand_lbftype'] ?? null,
				"id" => "schema:" . $options['generate_json_ld_brand_lbftype'] ?? null,
                "name"  => $options['generate_json_ld_localbusiness_brand_name'] ?? null,
                "logo"  => array(
                    "@type" => "ImageObject",
                    "url"   => $options['generate_json_ld_localbusiness_brand_logo_url'] ?? null,
                ),
            );
		$data["mainEntityOfPage"] = [
			"@type" => "WebPage",
			"@id" => "schema:WebPage"];
        return $data;
	}

    public function settings()
    {
        $settings = LocalBusinessSettings::instance();
        $settings->initDefaultSection();
        $settings->initSidebarSettingsPage(get_class($this));
        $settings->renderSidebarForm();
    }
}